"""add_theme_to_presentations

Revision ID: 7bdd5fd9eabf
Revises: 00b3c27a13bc
Create Date: 2026-03-25 18:52:10.116838

"""
from typing import Sequence, Union

from alembic import op  # type: ignore[import-not-found]
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bdd5fd9eabf'
down_revision: Union[str, None] = '00b3c27a13bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('presentations', sa.Column('theme', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('presentations', 'theme')
    # ### end Alembic commands ###
