OPENAI_URL = "https://api.openai.com/v1"

# Default models
DEFAULT_OPENAI_MODEL = "gpt-4.1"
DEFAULT_GOOGLE_MODEL = "models/gemini-2.5-flash"
DEFAULT_VERTEX_MODEL = "gemini-2.5-flash"
DEFAULT_AZURE_MODEL = "gpt-4.1"
DEFAULT_BEDROCK_MODEL = "us.anthropic.claude-3-5-haiku-20241022-v1:0"
DEFAULT_OPENROUTER_MODEL = "openai/gpt-4o"
DEFAULT_FIREWORKS_MODEL = "accounts/fireworks/models/llama-v3p1-8b-instruct"
DEFAULT_TOGETHER_MODEL = "openai/gpt-oss-20b"
DEFAULT_CEREBRAS_MODEL = "llama-3.3-70b"
DEFAULT_ANTHROPIC_MODEL = "claude-sonnet-4-20250514"
DEFAULT_LITELLM_MODEL = "gpt-4.1"
DEFAULT_LMSTUDIO_MODEL = "openai/gpt-oss-20b"
DEFAULT_CODEX_MODEL = "gpt-5.2"
