interface FastApiEnv {
  DEBUG?: string,
  CAN_CHANGE_KEYS?: string,
  LLM?: string,
  OPENAI_API_KEY?: string,
  OPENAI_MODEL?: string,
  GOOGLE_API_KEY?: string,
  GOOGLE_MODEL?: string,
  ANTHROPIC_API_KEY?: string,
  ANTHROPIC_MODEL?: string,
  OLLAMA_URL?: string,
  OLLAMA_MODEL?: string,
  CUSTOM_LLM_URL?: string,
  CUSTOM_LLM_API_KEY?: string,
  CUSTOM_MODEL?: string,
  PEXELS_API_KEY?: string,
  PIXABAY_API_KEY?: string,
  IMAGE_PROVIDER?: string,
  DISABLE_IMAGE_GENERATION?: string,
  EXTENDED_REASONING?: string,
  TOOL_CALLS?: string,
  DISABLE_THINKING?: string,
  WEB_GROUNDING?: string,
  DATABASE_URL?: string,
  DISABLE_ANONYMOUS_TRACKING?: string,
  COMFYUI_URL?: string,
  COMFYUI_WORKFLOW?: string,
  DALL_E_3_QUALITY?: string,
  GPT_IMAGE_1_5_QUALITY?: string,
  APP_DATA_DIRECTORY?: string,
  TEMP_DIRECTORY?: string,
  USER_CONFIG_PATH?: string,
}

interface NextJsEnv {
  NEXT_PUBLIC_FAST_API?: string,
  TEMP_DIRECTORY?: string,
  NEXT_PUBLIC_URL?: string,
  NEXT_PUBLIC_USER_CONFIG_PATH?: string,
  USER_CONFIG_PATH?: string,
  APP_DATA_DIRECTORY?: string,
}

interface UserConfig {
  CAN_CHANGE_KEYS?: string,
  LLM?: string,
  OPENAI_API_KEY?: string,
  OPENAI_MODEL?: string,
  GOOGLE_API_KEY?: string,
  GOOGLE_MODEL?: string,
  ANTHROPIC_API_KEY?: string,
  ANTHROPIC_MODEL?: string,
  OLLAMA_URL?: string,
  OLLAMA_MODEL?: string,
  CUSTOM_LLM_URL?: string,
  CUSTOM_LLM_API_KEY?: string,
  CUSTOM_MODEL?: string,
  PEXELS_API_KEY?: string,
  PIXABAY_API_KEY?: string,
  IMAGE_PROVIDER?: string,
  DISABLE_IMAGE_GENERATION?: string,
  EXTENDED_REASONING?: string,
  TOOL_CALLS?: string,
  DISABLE_THINKING?: string,
  WEB_GROUNDING?: string,
  DATABASE_URL?: string,
  DISABLE_ANONYMOUS_TRACKING?: string,
  COMFYUI_URL?: string,
  COMFYUI_WORKFLOW?: string,
  DALL_E_3_QUALITY?: string,
  GPT_IMAGE_1_5_QUALITY?: string,
  CODEX_MODEL?: string,
  CODEX_ACCESS_TOKEN?: string,
  CODEX_REFRESH_TOKEN?: string,
  CODEX_TOKEN_EXPIRES?: string,
  CODEX_ACCOUNT_ID?: string,
}

interface IPCStatus {
  success: boolean,
  message?: string,
}