"""template create info

Revision ID: 95b5127e93cd
Revises: 82abdbc476a7
Create Date: 2026-04-08 13:44:21.132802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '95b5127e93cd'
down_revision: Union[str, None] = '82abdbc476a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('template_create_infos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fonts', sa.JSON(), nullable=True),
    sa.Column('pptx_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('slide_htmls', sa.JSON(), nullable=False),
    sa.Column('slide_image_urls', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('template_create_infos')
    # ### end Alembic commands ###
