"""added_chat_history_messages_table

Revision ID: c7b70d0f31b1
Revises: 95b5127e93cd
Create Date: 2026-04-26 12:29:49.508761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c7b70d0f31b1'
down_revision: Union[str, None] = '95b5127e93cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_history_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('presentation_id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tool_calls', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['presentation_id'], ['presentations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_history_messages_conversation_id'), 'chat_history_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_chat_history_messages_position'), 'chat_history_messages', ['position'], unique=False)
    op.create_index(op.f('ix_chat_history_messages_presentation_id'), 'chat_history_messages', ['presentation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_history_messages_presentation_id'), table_name='chat_history_messages')
    op.drop_index(op.f('ix_chat_history_messages_position'), table_name='chat_history_messages')
    op.drop_index(op.f('ix_chat_history_messages_conversation_id'), table_name='chat_history_messages')
    op.drop_table('chat_history_messages')
    # ### end Alembic commands ###
