"""added_chat_history_messages_table

Revision ID: c7b70d0f31b1
Revises: 95b5127e93cd
Create Date: 2026-04-26 12:29:49.508761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c7b70d0f31b1'
down_revision: Union[str, None] = '95b5127e93cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _has_table(table_name: str) -> bool:
    return table_name in sa.inspect(op.get_bind()).get_table_names()


def _has_index(table_name: str, index_name: str) -> bool:
    inspector = sa.inspect(op.get_bind())
    if table_name not in inspector.get_table_names():
        return False
    return index_name in {index["name"] for index in inspector.get_indexes(table_name)}


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if not _has_table('chat_history_messages'):
        op.create_table(
            'chat_history_messages',
            sa.Column('id', sa.Uuid(), nullable=False),
            sa.Column('presentation_id', sa.Uuid(), nullable=False),
            sa.Column('conversation_id', sa.Uuid(), nullable=False),
            sa.Column('position', sa.Integer(), nullable=False),
            sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('content', sa.Text(), nullable=False),
            sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
            sa.Column('tool_calls', sa.JSON(), nullable=True),
            sa.ForeignKeyConstraint(
                ['presentation_id'], ['presentations.id'], ondelete='CASCADE'
            ),
            sa.PrimaryKeyConstraint('id'),
        )
    if not _has_index(
        'chat_history_messages', op.f('ix_chat_history_messages_conversation_id')
    ):
        op.create_index(
            op.f('ix_chat_history_messages_conversation_id'),
            'chat_history_messages',
            ['conversation_id'],
            unique=False,
        )
    if not _has_index(
        'chat_history_messages', op.f('ix_chat_history_messages_position')
    ):
        op.create_index(
            op.f('ix_chat_history_messages_position'),
            'chat_history_messages',
            ['position'],
            unique=False,
        )
    if not _has_index(
        'chat_history_messages', op.f('ix_chat_history_messages_presentation_id')
    ):
        op.create_index(
            op.f('ix_chat_history_messages_presentation_id'),
            'chat_history_messages',
            ['presentation_id'],
            unique=False,
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if _has_index(
        'chat_history_messages', op.f('ix_chat_history_messages_presentation_id')
    ):
        op.drop_index(
            op.f('ix_chat_history_messages_presentation_id'),
            table_name='chat_history_messages',
        )
    if _has_index(
        'chat_history_messages', op.f('ix_chat_history_messages_position')
    ):
        op.drop_index(
            op.f('ix_chat_history_messages_position'),
            table_name='chat_history_messages',
        )
    if _has_index(
        'chat_history_messages', op.f('ix_chat_history_messages_conversation_id')
    ):
        op.drop_index(
            op.f('ix_chat_history_messages_conversation_id'),
            table_name='chat_history_messages',
        )
    if _has_table('chat_history_messages'):
        op.drop_table('chat_history_messages')
    # ### end Alembic commands ###
