"""add theme column to presentations

Revision ID: f42ad4074449
Revises: 00b3c27a13bc
Create Date: 2026-03-24 12:42:32.369006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f42ad4074449'
down_revision: Union[str, None] = '00b3c27a13bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _has_column(table_name: str, column_name: str) -> bool:
    inspector = sa.inspect(op.get_bind())
    if table_name not in inspector.get_table_names():
        return False
    return column_name in {column["name"] for column in inspector.get_columns(table_name)}


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if not _has_column('presentations', 'theme'):
        op.add_column('presentations', sa.Column('theme', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if _has_column('presentations', 'theme'):
        op.drop_column('presentations', 'theme')
    # ### end Alembic commands ###
